Add the option to use ARM64
byu-oit/terraform-aws-scheduled-fargate pull request #14
Opened 2023-01-26 18:21 UTC by jvisker

2023-01-26 18:47 UTC, jvisker commented
Helps solve an issue here: https://github.com/byu-oit/appeng-questions/discussions/60

2023-01-26 18:56 UTC, GaryGSC requested changes
It looks like all the changes required to enable running on `ARM64` have been made.

I'm mainly comparing this to [the corresponding change to our Fargate APIs](https://github.com/byu-oit/terraform-aws-fargate-api/pull/38/files).

Over there, since we knew we were going to cut a new major version release, we required a newer version of Terraform and then also made several of our variables optional (thanks to the new capability for optional object attributes). We don't have to do that as part of this release, but we could.

This LGTM, if we consider it a major version bump.

2023-01-26 18:56 UTC, GaryGSC commented on main.tf
> +    aws = ">= 3.69"
This is a breaking change. I'd call this `v3.0.0`.

2023-01-26 18:56 UTC, GaryGSC commented on README.md
> +| cpu_architecture              | string                          | CPU architecture for the task definition. See docs for options
```suggestion
| cpu_architecture              | string                          | CPU architecture for the task definition. See [docs](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html#runtime-platform) for options                                                                                                                                                                                        | "X86_64"                     |
```

2023-01-27 02:26 UTC, joshgubler approved these changes

2023-01-27 16:16 UTC, GaryGSC approved these changes

2023-01-27 16:22 UTC, merged